### ISSUE TITLE
Make the program run at the beginning

### ISSUE THREAD

**Issue by blackmiaool** [june07/Node.js-inspector-Manager-NiM-#14]
I tried to solve this problem by [this](http://stackoverflow.com/questions/16420374/how-to-disable-in-the-node-debugger-break-on-first-line/43695541#43695541).

Is there any way better to solve it?

**Comment by june07** [comment]
Can you explain your issue a bit more...

**Comment by blackmiaool** [comment]
@june07   When the chrome-devtools is opened, the nodejs program pauses on the first line, so we have to click the start button by hand.

**Comment by june07** [comment]
Have you tried either removing --debug-brk or clearing any break points?

**Comment by blackmiaool** [comment]
@june07  Well... `--debug-brk` that's it.   Thanks a lot!
