### ISSUE TITLE
Optionally disable G+ elements

### ISSUE THREAD

**Issue by OliverUv** [june07/Node.js-inspector-Manager-NiM-#15]
NIM is currently unsuable in China without a complex proxy setup. It is probably also unusable on airplanes, or other times when the user has no Internet access.

Observed behavior: Click the NIM button. The animation that the button is clicked plays. Nothing else happens.

Expected behavior: Clicking the NIM button should bring up the NIM window.

I can open the option dialog, and I can open the NIM dialog when using a proxy, but when I use a proxy I can't access my local node inspector ports.

Proposed solution: Either set a manual timeout for fetching the G+ resources (maybe 0.2s) and continue operations if they haven't been loaded, or allow us to disable the G+ button in the options menu.

We (devs in China) already use a proxy for downloading and installing the extension, but when we are debugging our local apps we don't want Chromium to be running a proxy, because that changes 'localhost" to be our proxy endpoint. The usual workaround to this is to use a PAC file to specifically whitelist localhost, but this does not work in all versions of Chromium on all OSes. For example, I get the following when I  try to open the networking dialog:

```
When running Chromium under a supported desktop environment, the
system proxy settings will be used. However, either your system is not
supported or there was a problem launching your system configuration.

But you can still configure via the command line. Please see man
chromium-browser for more information on flags and environment
variables.
```

I can start Chromium with `--proxy-server=socks5://localhost:1080` to use a SOCKS proxy, but for this I do not get any opportunity to configure black/whitelists, and I can't configure a global system proxy (for reasons I don't want to get into.)

**Comment by OliverUv** [comment]
Oh, and if you are using external scripts like lodash or jQuery are loaded from Google's CDN at runtime instead of being bundled, that too would need to be changed for this to work in China / without connectivity.

**Comment by june07** [comment]
How have you confirmed that the fetching of external G+ resources is the cause of the problem?  Do you have any logs?  I'd like to be able to duplicate the issue on my end.  Currently, if I disable network connectivity (via proxy settings to block all) I still get the popup just fine.

Any additional information you can provide will help...

**Comment by OliverUv** [comment]
Oh, I have not made 100% sure. I'll get to that in maybe 2 months time, when some deadlines are over.

The GFW (great firewall) usually doesn't kill connections outright. It will notice a bad connection and gradually strangle transfer speeds, causing infinite loading. So the behavior is not identical to having no connectivity.

Glad to hear it works offline, that's a pretty essential requirement.

**Comment by OliverUv** [comment]
(You can close the issue if you want & I can create a new one if/when it becomes relevant)
