### ISSUE TITLE
Keeps stealing focus from other apps

### ISSUE THREAD

**Issue by nvreez** [june07/Node.js-inspector-Manager-NiM-#16]
I'm using nodemon and with every update to my node files the inspector grabs focus from my editor. I've got the "Make tab active" option disabled, which works when focus is already on Chrome. Would love if the option also prevented Chrome from grabbing focus while in my editor. Is this possible or native Chrome behaviour when refreshing a tab?
I'm using Mac OS 10.11.6 with Sublime 3 and Chrome 59 (beta channel). Love the plugin btw.

**Comment by june07** [comment]
Will be looking into a resolution for this soon.

**Comment by june07** [comment]
Update fix coming today.

**Comment by june07** [comment]
Webstore has been updated with version 0.13.8... check it out.  https://june07.com/nim
