### ISSUE TITLE
Extension crashes on clicking on the extension icon

### ISSUE THREAD

**Issue by EdwardDiehl** [june07/Node.js-inspector-Manager-NiM-#17]
Thanks a lot for such useful tool!

Unfortunately at some point the extension started crashing on my machine when i click on it (Ubuntu 16.04, Chrome 59). Maybe you have any idea where is the source of this issue?

**Comment by june07** [comment]
Try uninstalling/reinstalling...

**Comment by EdwardDiehl** [comment]
First i tried to repair it, after click on 'repair' the extension appeared again, but problem is still there: click -> crash. Reinstall also didn't solve the problem.
The same issue is on my another computer, also Ubuntu 16.04, chrome Version 59.0.3071.86 (Official Build) (64-bit). But i had the same issue on previous version of chrome

**Comment by june07** [comment]
Which version of NiM are you running?

**Comment by EdwardDiehl** [comment]
@june07 Version 0.13.8

**Comment by june07** [comment]
https://twitter.com/june07t/status/876895182565687296

**Comment by june07** [comment]
Working on getting some traction with the DevTools team...

**Comment by aschrijver** [comment]
@june07 I can confirm this error on Ubuntu 16.04 (NiM 0.13.8, Chrome 59.0.3071.115, Node 8.1.2). The plugin gets corrupted on the first click on the item.
Repairing and avoiding clicking the icon the plugin seems to be working, until the connection is broken as described in your Chromium bug report.
However, I was under the impression (maybe wrongly) that a bug in Node was causing this behaviour: https://github.com/nodejs/node/issues/7593

**Comment by june07** [comment]
Thank you for this insight.  I will look more into the node bug.  I certainly want to get the issue fixed as it is something many are seeing and the assumption is that the problem is with NiM.  Again, thanks.  Hopefully, a resolution can be found soon.

**Comment by june07** [comment]
Node was causing this behaviour: nodejs/node#7593

**Comment by fullofcaffeine** [comment]
Hi! This is happening for me as well. Linux Mint 18.3, Chrome Version 66.0.3359.181 (Official Build) (64-bit) and nodejs v8.10.0. Extension stopped working, if I click it it disappears and Chrome then tells it's corrupted :(

**Comment by Slapbox** [comment]
Same issues with Node 8.9.3, Linux Mint 18.3. Node 10.9.x works fine, but I really need to use Node 8 in this case. Any ideas @june07 ?

**Comment by Slapbox** [comment]
Node 8.11.4 works. I can probably make this work. Thanks for the great project @june07
