### ISSUE TITLE
Auto-open setting is not remembered on chrome restart

### ISSUE THREAD

**Issue by ptim** [june07/Node.js-inspector-Manager-NiM-#18]
I leave NIM enabled in the Chrome Extensions settings, and NIM set to 'manual'.

I find that whenever I restart my computer and load up my work project (has a couple of `node --inspect` tasks) the devtools window opens up, and I set NIM to 'manual' again, then shut devtools until I need it some other day...

No biggie, just an FYI - thanks!

**Comment by june07** [comment]
Thank you.  Will look into this.  Are you running the most recent version?

**Comment by ptim** [comment]
sorry, missed your reply.. just noticed I had two versions: 0.13.8 and 0.13.2-Beta1.. 

have now removed the beta... and can confirm this is still happening on 0.13.8 :)

**Comment by june07** [comment]
I'm unable to duplicate this on my end.  To be clear, I am setting auto-open to "Manual" and restarting Chrome.  When I re-open NiM by clicking the icon after Chrome has restarted, the setting remains as it was previously set...

As I understand your problem, you are seeing auto-open setting itself to "Auto" on Chrome restart correct?

**Comment by june07** [comment]
Fixed https://github.com/june07/Node.js-inspector-Manager-NiM-/pull/30.

I think I may have been misunderstanding your problem.  What I was seeing was that disabling/enabling NiM would cause the auto-open to reset back to "Auto".  The setting was not being saved.

I will be pushing the change to the web store shortly.
