### ISSUE TITLE
Uses a lot of CPU

### ISSUE THREAD

**Issue by wmertens** [june07/Node.js-inspector-Manager-NiM-#20]
When NiM is in auto mode, I can often see it take up 15% of CPU in the Chrome task manager. Can this not be lessened?

Even when I switch to manual mode, the extension takes up 0.1% CPU even though it shouldn't be doing anything…

(BTW, great extension! 👍 🙇)

**Comment by june07** [comment]
Thank you for the feedback.

I could definitely use some help, so feel free to issue a PR for the fix.  ;)

**Comment by wmertens** [comment]
:) any idea what could cause it?

**Comment by june07** [comment]
The only thing I can think of off hand is the polling.  I wrote a back off
function but still that might be the issue.

I haven't had a chance to try to duplicate the problem yet myself.

**Comment by wmertens** [comment]
In the mean time, Chrome built-in inspector detection got good, and I haven't needed NiM any more… Thank you for your work!

**Comment by wmertens** [comment]
In the meantime, Chrome has gotten very good at Node debugging, and I don't
need this extension any more. Chrome doesn't seem to suffer from CPU usage
while polling.

To use it, go to chrome://inspect and click on the "dedicated devtools for
chrome" link. There, in the connections tab, you can specify hosts and
ports, I only tried with localhost. When you're running node with
--inspect, you can either go to chrome://inspect or you should be able to
click on a little node icon in the top left of the web devtools.

Thank you for the work you put in this extension, it was very nice to have
it!
