### ISSUE TITLE
NiM inappropriately intercepts `cmd+i`

### ISSUE THREAD

**Issue by clayzermk1** [june07/Node.js-inspector-Manager-NiM-#21]
### Environment
OS X 10.12.6 (16G29)
Chrome 60.0.3112.90 (Official Build) (64-bit)
NiM 0.13.8

### What happened?
After installing NiM, I was working in Google Docs and attempted to use `cmd+i` to italicize some text but nothing happened. Disabling NiM, `cmd+i` worked again. Inspecting `manifest.json`, I noticed that [`cmd+i` was registered as the open devtools keyboard shortcut](https://github.com/june07/Node.js-inspector-Manager-NiM-/blob/25835e4d5e0bd1d1dc83cceabe4c81306af8cbb6/manifest.json#L41) when it should be `cmd+option+i` (View -> Developer -> Developer Tools ⌥⌘I).

### What did you expect to happen?
I did not expect NiM to intercept keyboard shortcuts.

---

Thank you for NiM, for the reasons you outline in your blog post it's a real time saver. 🍻

**Comment by june07** [comment]
That is actually expected functionality.  If you would like to change the shortcut or disable it, you can do that from Chrome (bottom of extensions page "Keyboard shortcuts").

cmd+option+i is the shortcut for devtools and has nothing to do with NiM.

Sorry for the late response on this.  Been super busy!

**Comment by clayzermk1** [comment]
Hi @june07, thanks for the reply.

I don't think I explained the problem clearly. If you look at the line of code I linked, NiM registers `cmd+i` (the OS X keyboard shortcut for italics in WYSIWYG editors like Gmail or Google Docs) as "open devtools". I feel that when the NiM extension is enabled, I should be able to have normal use of a common keyboard shortcut such as `cmd+i` in an unrelated tab such as Gmail. As it is now, `cmd+i` is rendered non-functional in all of Chrome when NiM is enabled.

I think a more obscure keyboard shortcut such as `cmd+option+shift+i` would be more appropriate and would not conflict with pages that have keybindings for `cmd+i`.

Thanks again for NiM, total lifesaver.

Don't work too hard 🍻

**Comment by june07** [comment]
Clay,

Totally understand where you are coming from.  In which case you can change
the setting to whatever you like (ie "cmd+option+shift+i"), see screenshot.

I get what you are saying about common keyboard shortcuts, however you're
the first person to mention this.  I personally never use the italics
shortcut (or italics very much for that matter).  And for a developer who
doesn't use the shortcut, I felt it was better to use a common, but least
used shortcut.

Hey, thanks for the great feedback and thanks.  It's very much appreciated
and keeps me going.




<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by ianstormtaylor** [comment]
Took me forever to figure out what extension was blocking the `cmd+i` shortcut in _every_ rich text editor I use on any website... this is a bad decision.

**Comment by june07** [comment]
A solution which should satisfy all.  https://github.com/june07/Node.js-inspector-Manager-NiM-/pull/31  Would love some feedback, particularly from @ianstormtaylor .  Thanks.

**Comment by june07** [comment]
Pushed.

**Comment by clayzermk1** [comment]
@june07 I just reinstalled and tried it out, I think #31 is a fine compromise of principles. I think this will help people who are caught off guard. Then they can figure out how to change/disable the shortcut.

Thanks again!
