### ISSUE TITLE
Unable to group by Windows folders

### ISSUE THREAD

**Issue by f-w** [june07/Node.js-inspector-Manager-NiM-#23]
![image](https://user-images.githubusercontent.com/12823994/29836144-29ac8a9e-8ca9-11e7-8b94-961501ae8545.png)

In contrast, node-inspector can

![image](https://user-images.githubusercontent.com/12823994/29836394-f8cbafd0-8ca9-11e7-8b68-19266d07cea7.png)

**Comment by june07** [comment]
[
<img width="469" alt="screen shot 2017-10-15 at 3 31 37 pm" src="https://user-images.githubusercontent.com/11353590/31589951-25235f4a-b1be-11e7-80a1-1714b787a7cf.png">
](url)

Pretty sure the issue you are seeing has nothing to do with NiM itself but rather the version of DevTools you happened to be running.  Either way, there should be an option to change the behavior as shown in the screenshot.
