### ISSUE TITLE
force redirected remote url

### ISSUE THREAD

**Issue by fatkhanfauzi** [june07/Node.js-inspector-Manager-NiM-#24]
![image](https://user-images.githubusercontent.com/2447205/30167191-cddf4bd4-940f-11e7-87de-1d9fb2566de4.png)

i'm facing the same issue.
is there any way to do that ?

**Comment by june07** [comment]
Fatkhanfauzi, thanks for the GitHub contribution.  I will merge it soon, just have to check something.  Have you tested the change locally yet?

**Comment by june07** [comment]
Merged commit and pushed update to Google Web Store.

**Comment by fatkhanfauzi** [comment]
sorry for the late reply.. yes i have been using it my solution locally :)
thanks for merging that in..
