### ISSUE TITLE
Inspecting Jest breaks opening devtools

### ISSUE THREAD

**Issue by nickmccurdy** [june07/Node.js-inspector-Manager-NiM-#28]
When using Jest's recommended inspection command (`node --inspect-brk node_modules/.bin/jest -i`), automatic mode does not open devtools and manual mode causes an error.

### Automatic
- Use automatic mode
- Run command
- DevTools are not opened

### Manual
- Use manual mode
- Run command
- Click Open DevTools
- Error is displayed: `TYPEERROR: CANNOT READ PROPERTY '0' OF NULL`

## Environment
- NiM 0.13.9
- Chrome Dev 63.0.3230.0
- Jest 21.2.1
- Node 8.6.0

**Comment by june07** [comment]
Nick, can you try the update I just pushed (0.13.10)...

Yesterday's push introduced a bug.  Should be resolved now.  I will push the GitHub update in a bit.

**Comment by nickmccurdy** [comment]
Thanks for the fast response! I reinstalled the extension and now automatic mode works perfectly, but if I set the extension to manual mode first and click Open Devtools I get an `OPENING TAB IN PROGRESS...` error.

**Comment by june07** [comment]
Nick,

That is actually a known issue and I'm almost sure has to do with a different library/project (https://github.com/ChromeDevTools/devtools-frontend/issues/26) or https://bugs.chromium.org/p/chromium/issues/detail?id=734615#c7

Can you try disabling the extension and then reenabling and/or uninstall/reinstall and see if that helps.  I can't duplicate the issue on my end at this time.
